global:
  marketplace-ami: false
  owner: jorge@aviatrix.com
  qsname: quickstart-aviatrix
  regions:
    - us-east-1
    - us-east-2
  reporting: true
tests:
  quickstart-aviatrix:
    parameter_input: quickstart-aviatrix-params.json
    template_file: quickstart-aviatrix.template
  quickstart-aviatrix-master:
    parameter_input: quickstart-aviatrix-master-params.json
    template_file: quickstart-aviatrix-master.template
